<?php
/*
Plugin Name: My Custom CSS
Plugin URI: https://wordpress.org/plugins/my-custom-css/
Description: With this plugin you can put custom css code without edit your theme and/or your plugins (really useful in case of any theme/plugin update).
It contain also <a href="https://ace.c9.io/">Ace (Ajax.org Cloud9 Editor)</a> Code Editor for write a good css code.
You can see in action (source code) here: <a href="http://www.vegamami.it/">VegAmami</a> :)
PS: support file backup and - very important - static css file (fantastic for performance) ;)
Author: DarkWolf
Version: 2.7
Author URI: https://laltroweb.it/
Text Domain: my-custom-css
*/

// Prevent Direct Access with homepage redirect
if (!defined('DB_NAME'))
{
	header('Location: http://'.$_SERVER['SERVER_NAME'].'/');
}

// Text Domain: my-custom-css
load_plugin_textdomain('my-custom-css', false, dirname(plugin_basename(__FILE__)) . '/lang/');


function mystylecss_basedir()
{
	$upload_dir = wp_upload_dir();
	$mystylecss_basedir = $upload_dir['basedir'];
	return $mystylecss_basedir;
}
function mystylecss_url()
{
	$upload_dir = wp_upload_dir();
	$mystylecss_url = set_url_scheme($upload_dir['baseurl']);
	return $mystylecss_url;
}

// Fix old backup folder or no exist
if (!is_dir(mystylecss_basedir().'/my_custom_css/bkk'))
{
	wp_mkdir_p(mystylecss_basedir().'/my_custom_css/bkk');
}
// And Blank index.html to prevent listing directory
else if(!file_exists(mystylecss_basedir()."/my_custom_css/index.html") || !file_exists(mystylecss_basedir()."/my_custom_css/bkk/index.html"))
{
	file_put_contents(mystylecss_basedir()."/my_custom_css/index.html", "<!-- Prevent Directory Listing -->");
	file_put_contents(mystylecss_basedir()."/my_custom_css/bkk/index.html", "<!-- Prevent Directory Listing -->");
}

// Generate my_style_id url:
function my_style_id()
{
	$blog_id = get_current_blog_id(); $cssid = ( $blog_id > "1" ) ? $cssid = "_id-".$blog_id : $cssid = null;
	$my_style_id = "/my_custom_css/my_style".$cssid.".css";
	return $my_style_id;
}

// Generate css url:
function css_url()
{
	$css_url = mystylecss_url().my_style_id();
	return $css_url;
}

// Generate css path:
function css_path()
{
	$css_path = mystylecss_basedir().my_style_id();
	return $css_path;
}

// make my_style.css and write write css code!
function mycustomcss()
{
	// Strip tag for security reason!
	$mycustomcss = strip_tags(get_option('my_custom_css'));
	return $mycustomcss;
}

function mycustomcss_head()
{
	$mycustomcss = mycustomcss();
	if (!empty($mycustomcss))
	{
		// Write in source!
		echo "\n<!-- My Custom CSS -->\n<link rel='stylesheet' id='mccss_stylesheet' href='".css_url()."?".@filemtime(css_path())."' type='text/css' media='all' />\n<!-- My Custom CSS -->\n";
	}
}

function makecss()
{
	$makecss = file_put_contents(css_path(), "/********* Do not edit this file *********/\n/*\nMy Custom CSS - Maked by Salvatore Noschese\na.k.a. L'altroWeb - https://laltroweb.it/\n*/\n/********* Do not edit this file *********/\n\n".mycustomcss());
	return $makecss;
}

// Fix first upgrade from old release or manual my_style.css deletion!
if (!file_exists(css_path()))
{
	makecss();
}

// Start Add link on plugins page
function mycustomcss_links($links)
{ 
	# Settings:
	$settings_link = '<a href="admin.php?page=my_custom_css" title="My Custom CSS">'.__('Settings','my-custom-css').'</a>';
	array_unshift($links, $settings_link);
	# Support:
	$support_forum = '<a href="https://laltroweb.it/" title="laltroweb.it">'.__('Support','my-custom-css').'</a>';
	array_unshift($links, $support_forum);
	# return:
	return $links;
}
function add_plugin_meta_links($links, $file)
{
	if ($file == plugin_basename(__FILE__))
	{
		$links[] = '<a href="https://www.paypal.me/SalvatoreN" title="Buy Me a Beer ;)">Donate :)</a>';
	}
	return $links;
}
// End Add link on plugins page

// Change the CSS for this plugin on admin plugins page
function mycustomcss_admin_style()
{
	global $pagenow;
	if ($pagenow == "plugins.php")
	{
		echo "<style type='text/css'>\n#my-custom-css td.plugin-title strong {\n\tbackground: url('".plugin_dir_url(__FILE__)."/mccss.png') no-repeat scroll 115px 2px;\n}\n#my-custom-css div.row-actions-visible {\n\tpadding-top: 15px;\n}\n#my-custom-css div.plugin-version-author-uri {\n\tbackground-color: #EAEAEA;\n\tborder-radius: 5px;\n\tbox-shadow: 0 8px 6px -6px gray; \n\tfont-weight: bold; \n\tpadding: 7px; \n\tmargin-bottom: 12px;\n}\n</style>\n";
	}
}


// Make backup when save!
if(isset($_POST['save']))
{
	$directory = mystylecss_basedir()."/my_custom_css/bkk/*.css";
	if (glob($directory) != false)
	{
		$filecount = count(glob($directory))+1;
	}
	else
	{
		$filecount = 1;
	}
	$oldname = css_path();
	$newname = mystylecss_basedir().'/my_custom_css/bkk/' . ( $filecount ++ ) . $cssid . '_' . filemtime($oldname) .'.css';
	rename($oldname, $newname);
}

// View backup (view only css)
if(isset($_POST['viewbackup']))
{
	$directory = mystylecss_basedir()."/my_custom_css/bkk/";
	$files=array();
	if ($dh=opendir($directory))
	{
		while (($file=readdir($dh))!==false)
		if ($file!="." && $file!=".." && preg_match("/\.(css)$/", $file))
			$files[filemtime($directory.$file)]=$file;
		closedir($dh);
	}

	krsort($files);
	reset($files);
	$href = mystylecss_url()."/my_custom_css/bkk/";
	date_default_timezone_set(ini_get('date.timezone') ? ini_get('date.timezone') : 'UTC');

echo '
<!DOCTYPE html>
<html>
  <head>
    <title>' .  __('My custom CSS - Backup','my-custom-css') . '</title>
  </head>
	<body style="background: #F1F1F1; padding: 20px; width: 90%; margin: 20px auto; border: 1px 0 dotted gray">';
	if (glob($directory."*.css") == false)
	{
	echo '
	<input type="button" value="' .  __('Close now!','my-custom-css') . '" onclick="self.close()" style="margin: 0px 20px; float: right" />
	<br />
	<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
		' .  __("I can't list any *.css: 'No file found'... ","my-custom-css") . '
	</div>';
	}
	else
	{
	echo '
	<form method="post" action="'. admin_url( 'admin.php' ) .'?action=my_custom_css?erase_backup" style="margin-right: 20px; float: right">
		<input type="button" value="' .  __('Close now!','my-custom-css') . '" onclick="self.close()" style="padding: 2px 5px" />
		 | 
		<input type="submit" name="erasebackup" class="button" value="' .  __('Erase all backup','my-custom-css') . '" style="color: red; padding: 2px 5px" onclick="return confirm(\'' .  __('Do you want really delete all backup?','my-custom-css') . '\');" />
	</form>
	<br />';
	while (list($date,$file)=each($files))
	echo '
	<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
	<p><b>' .  __('File:','my-custom-css') . '</b> <a href="'.$href.$file.'">'.$href.$file.'</a></p>
	<p><b>' .  __('Path:','my-custom-css') . '</b> '.$directory.$file.'</p>
	<p><b>' .  __('Saved:','my-custom-css') . '</b> '.date("M d Y | h:i:s (a)",current_time($date)).'</p>
	<p><b>' .  __('Size:','my-custom-css') . '</b> '.(round(filesize($directory.$file). " bytes")).' bytes</p>
	</div>';
	}
	echo '
  </body>
</html>';
}


// Erase backup:
if(isset($_POST['erasebackup']))
{
echo '
<!DOCTYPE html>
<html>
  <head>
    <title>' .  __('My custom CSS - Erase Backup','my-custom-css') . '</title>
  </head>
	<body style="background: #F1F1F1; padding: 20px; width: 90%; margin: 20px auto; border: 1px 0 dotted gray">';
	$glob = glob(mystylecss_basedir()."/my_custom_css/bkk/*.css");
	if ($glob == false)
	{
	echo '
	<input type="button" value="' .  __('Close now!','my-custom-css') . '" onclick="self.close()" style="margin: 0px 20px; float: right" />
	<br />
	<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
		' .  __("I can't delete any *.css: 'No file found'... ","my-custom-css") . '
	</div>';
	}
	else
	{
		echo '
		<input type="button" value="' .  __('Close now!','my-custom-css') . '" onclick="self.close()" style="margin: 0px 20px; float: right" />
		<br />';
		foreach (glob(mystylecss_basedir()."/my_custom_css/bkk/*.css") as $filename)
		{
		echo '
		<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
			'.$filename.' - ' . filesize($filename) . '' .  __('bytes, was successfully deleted!!!','my-custom-css') . '
		</div>';
		unlink($filename);
		}
	}
		echo '
  </body>
</html>';
}

function set_theme()
{
	if (isset($_POST["themelist"]) && !empty($_POST["themelist"]))
	{
		$settheme = $_POST["themelist"];
	}
	else if (!isset($_COOKIE['_mccss_ace_themelist_']))
	{
		$settheme = 'ace/theme/chrome';
	}
	else
	{
		$settheme = $_COOKIE['_mccss_ace_themelist_'];
	}
	return $settheme;
}

// Option page code:
function mycustomcss_scripts()
{
echo '
<!-- Start My Custom CSS Code -->
<!-- Ace Editor -->
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/ace.js" charset="utf-8"></script>
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/ext-searchbox.js" charset="utf-8"></script>
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/ext-language_tools.js" charset="utf-8"></script>
<script type="text/javascript">
// Ace Setting
( function( global, $ ) {
	var editor,
		syncCSS = function() {
			$( \'#my_custom_css_textarea\' ).val( editor.getSession().getValue() );
		},
		loadAce = function() {
			editor = ace.edit( \'my_custom_css\' );
			editor.session.setMode("ace/mode/css");
			global.safecss_editor = editor;
			editor.getSession().setUseWrapMode( true );
			editor.setShowPrintMargin( false );
			editor.getSession().setValue( $( \'#my_custom_css_textarea\' ).val() );
			editor.setOptions({maxLines: Infinity});
			editor.setTheme("'.set_theme().'");
			editor.setOptions({minLines: 10});
			editor.execCommand("find");
			// enable autocompletion and snippets
			ace.require("ace/ext/language_tools");
				editor.setOptions({
				enableBasicAutocompletion: true,
				enableSnippets: true,
				enableLiveAutocompletion: true
			});
			jQuery.fn.spin&&$( \'#my_custom_css_container\' ).spin( false );
			$( \'#my-custom-css\' ).submit( syncCSS );
		};
	if ( $.browser.msie&&parseInt( $.browser.version, 10 ) <= 7 ) {
		$( \'#my_custom_css_container\' ).hide();
		$( \'#my_custom_css_textarea\' ).show();
		return false;
	} else {
		$( global ).load( loadAce );
	}
	global.aceSyncCSS = syncCSS;
} )( this, jQuery );
</script>
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/_scrolltop.js"></script>
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/textresizer/cookie.js"></script>
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/textresizer/textresizer.min.js"></script>
<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/textresizer/textresizer_target.js"></script>
<!-- CSS Code -->
<link rel="stylesheet" id="ace-editor-custom-css" href="'.plugin_dir_url(__FILE__).'editor/ace_custom.css" type="text/css" media="all" />
<!-- End My Custom CSS Code -->
';
}
// Register Settings
function mycustomcss_registersetting()
{
	register_setting('mccss_settings','my_custom_css');
}

// Textarea/Form:
function mccss_options()
{
	// Get plugin version:
	$plugin_data = get_plugin_data(__FILE__);
	$plugin_version = $plugin_data['Version'];
	
	// BrightTheme
	$chrome = 'ace/theme/chrome';
	$clouds = 'ace/theme/clouds';
	$crimson_editor = 'ace/theme/crimson_editor';
	$dawn = 'ace/theme/dawn';
	$dreamweaver = 'ace/theme/dreamweaver';
	$eclipse = 'ace/theme/eclipse';
	$github = 'ace/theme/github';
	$iplastic = 'ace/theme/iplastic';
	$solarized_light = 'ace/theme/solarized_light';
	$textmate = 'ace/theme/textmate';
	$tomorrow = 'ace/theme/tomorrow';
	$xcode = 'ace/theme/xcode';
	$kuroir = 'ace/theme/kuroir';
	$katzenmilch = 'ace/theme/katzenmilch';
	$sqlserver = 'ace/theme/sqlserver';
	// DarkTheme
	$ambiance = 'ace/theme/ambiance';
	$chaos = 'ace/theme/chaos';
	$clouds_midnight = 'ace/theme/clouds_midnight';
	$cobalt = 'ace/theme/cobalt';
	$idle_fingers = 'ace/theme/idle_fingers';
	$kr_theme = 'ace/theme/kr_theme';
	$merbivore = 'ace/theme/merbivore';
	$merbivore_soft = 'ace/theme/merbivore_soft';
	$mono_industrial = 'ace/theme/mono_industrial';
	$monokai = 'ace/theme/monokai';
	$pastel_on_dark = 'ace/theme/pastel_on_dark';
	$solarized_dark = 'ace/theme/solarized_dark';
	$terminal = 'ace/theme/terminal';
	$tomorrow_night = 'ace/theme/tomorrow_night';
	$tomorrow_night_blue = 'ace/theme/tomorrow_night_blue';
	$tomorrow_night_bright = 'ace/theme/tomorrow_night_bright';
	$tomorrow_night_eighties = 'ace/theme/tomorrow_night_eighties';
	$twilight = 'ace/theme/twilight';
	$vibrant_ink = 'ace/theme/vibrant_ink';

echo '
<div class="wrap">
	<h2>' .  __('My Custom CSS Panel','my-custom-css') . ' - v'.$plugin_version.'</h2>
		<div id="textsizer">
			<p>' .  __('Font Size:','my-custom-css') . '</p>
				<ul class="textresizer">
				  <li><a href="#nogo" class="small-text" title="12px (Small)">A-</a></li>
				  <li><a href="#nogo" class="medium-text" title="14px (Medium)">A</a></li>
				  <li><a href="#nogo" class="large-text" title="16px (Large)">A+</a></li>
				  <li><a href="#nogo" class="larger-text" title="18px (Larger)">A++</a></li>
				  <li><a href="#nogo" class="giga-text" title="26px (Giga)">A+++</a></li>
				</ul>
		</div>
		<form action="'.admin_url( 'admin.php' ).'?page=my_custom_css" method="post" id="thememenu">
			<label for="theme">' .  __('Theme:','my-custom-css') . '</label>
				<select name="themelist" id="themelist" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}">
					<optgroup label="' .  __('Bright:','my-custom-css') . '">
						<option value="'.$chrome.'"'.(set_theme() == $chrome ? ' selected="selected"' : false).'>Chrome</option>
						<option value="'.$clouds.'"'.(set_theme() == $clouds ? ' selected="selected"' : false).'>Clouds</option>
						<option value="'.$crimson_editor.'"'.(set_theme() == $crimson_editor ? ' selected="selected"' : false).'>Crimson Editor</option>
						<option value="'.$dawn.'"'.(set_theme() == $dawn ? ' selected="selected"' : false).'>Dawn</option>
						<option value="'.$dreamweaver.'"'.(set_theme() == $dreamweaver ? ' selected="selected"' : false).'>Dreamweaver</option>
						<option value="'.$eclipse.'"'.(set_theme() == $eclipse ? ' selected="selected"' : false).'>Eclipse</option>
						<option value="'.$github.'"'.(set_theme() == $github ? ' selected="selected"' : false).'>GitHub</option>
						<option value="'.$iplastic.'"'.(set_theme() == $iplastic ? ' selected="selected"' : false).'>IPlastic</option>
						<option value="'.$solarized_light.'"'.(set_theme() == $solarized_light ? ' selected="selected"' : false).'>Solarized Light</option>
						<option value="'.$textmate.'"'.(set_theme() == $textmate ? ' selected="selected"' : false).'>TextMate</option>
						<option value="'.$tomorrow.'"'.(set_theme() == $tomorrow ? ' selected="selected"' : false).'>Tomorrow</option>
						<option value="'.$xcode.'"'.(set_theme() == $xcode ? ' selected="selected"' : false).'>XCode</option>
						<option value="'.$kuroir.'"'.(set_theme() == $kuroir ? ' selected="selected"' : false).'>Kuroir</option>
						<option value="'.$katzenmilch.'"'.(set_theme() == $katzenmilch ? ' selected="selected"' : false).'>KatzenMilch</option>
						<option value="'.$sqlserver.'"'.(set_theme() == $sqlserver ? ' selected="selected"' : false).'>SQL Server</option>
					</optgroup>
					<optgroup label="' .  __('Dark:','my-custom-css') . '">
						<option value="'.$ambiance.'"'.(set_theme() == $ambiance ? ' selected="selected"' : false).'>Ambiance</option>
						<option value="'.$chaos.'"'.(set_theme() == $chaos ? ' selected="selected"' : false).'>Chaos</option>
						<option value="'.$clouds_midnight.'"'.(set_theme() == $clouds_midnight ? ' selected="selected"' : false).'>Clouds Midnight</option>
						<option value="'.$cobalt.'"'.(set_theme() == $cobalt ? ' selected="selected"' : false).'>Cobalt</option>
						<option value="'.$idle_fingers.'"'.(set_theme() == $idle_fingers ? ' selected="selected"' : false).'>idle Fingers</option>
						<option value="'.$kr_theme.'"'.(set_theme() == $kr_theme ? ' selected="selected"' : false).'>krTheme</option>
						<option value="'.$merbivore.'"'.(set_theme() == $merbivore ? ' selected="selected"' : false).'>Merbivore</option>
						<option value="'.$merbivore_soft.'"'.(set_theme() == $merbivore_soft ? ' selected="selected"' : false).'>Merbivore Soft</option>
						<option value="'.$mono_industrial.'"'.(set_theme() == $mono_industrial ? ' selected="selected"' : false).'>Mono Industrial</option>
						<option value="'.$monokai.'"'.(set_theme() == $monokai ? ' selected="selected"' : false).'>Monokai</option>
						<option value="'.$pastel_on_dark.'"'.(set_theme() == $pastel_on_dark ? ' selected="selected"' : false).'>Pastel on dark</option>
						<option value="'.$solarized_dark.'"'.(set_theme() == $solarized_dark ? ' selected="selected"' : false).'>Solarized Dark</option>
						<option value="'.$terminal.'"'.(set_theme() == $terminal ? ' selected="selected"' : false).'>Terminal</option>
						<option value="'.$tomorrow_night.'"'.(set_theme() == $tomorrow_night ? ' selected="selected"' : false).'>Tomorrow Night</option>
						<option value="'.$tomorrow_night_blue.'"'.(set_theme() == $tomorrow_night_blue ? ' selected="selected"' : false).'>Tomorrow Night Blue</option>
						<option value="'.$tomorrow_night_bright.'"'.(set_theme() == $tomorrow_night_bright ? ' selected="selected"' : false).'>Tomorrow Night Bright</option>
						<option value="'.$tomorrow_night_eighties.'"'.(set_theme() == $tomorrow_night_eighties ? ' selected="selected"' : false).'>Tomorrow Night 80s</option>
						<option value="'.$twilight.'"'.(set_theme() == $twilight ? ' selected="selected"' : false).'>Twilight</option>
						<option value="'.$vibrant_ink.'"'.(set_theme() == $vibrant_ink ? ' selected="selected"' : false).'>Vibrant Ink</option>
					</optgroup>
				</select>
		</form>';
		if (isset($_POST["themelist"]) && !empty($_POST["themelist"]))
		{
			setcookie('_mccss_ace_themelist_', $_POST['themelist'], time()+31556926 ,'/');
		}
	echo'
	<form id="my-custom-css" method="post" action="options.php">';
	settings_fields( 'mccss_settings' );
echo '
		<div id="my_custom_css_container">
			<div name="my_custom_css" id="my_custom_css"></div>
		</div>
		<textarea id="my_custom_css_textarea" name="my_custom_css" style="display: none;">'.get_option('my_custom_css').'</textarea>
		<input type="submit" name="save" class="button-primary" value="' .  __('Save','my-custom-css') . '" />
	</form>
	<div id="mccss_credit">
		<a href="https://wordpress.org/plugins/my-custom-css/" title="My Custom CSS">My Custom CSS v'.$plugin_version.'</a> | Author: <a href="https://laltroweb.it/" title="Salvatore Noschese - (L\'AltroWeb)">Salvatore Noschese</a> - Support my work: <a href="https://www.paypal.me/SalvatoreN" title="Even 1$ can help... :)">Donate :)</a>
	</div>';

// Hidden view/erase button for blog id > 1 (security fix in multisite)
$blog_id = get_current_blog_id();
if($blog_id == 1)
{
	// If no backup exist, disable button!
	$glob = glob(mystylecss_basedir()."/my_custom_css/bkk/*.css");
	if ($glob == false) { $submit_backup = 'value="' .  __('No backup found...','my-custom-css') . '" title="' .  __('No backup found...','my-custom-css') . '" disabled'; }
	else { $submit_backup = 'value="' .  __('View backups :)','my-custom-css') . '" title="' .  __('Click to view all backups!','my-custom-css') . '" '; }
echo '
	<form method="post" action="'.admin_url( 'admin.php' ).'?action=my_custom_css?show_backup" target="_blank">
		<input type="submit" name="viewbackup" class="button-secondary" '.$submit_backup.' />
	</form>';
}
echo '
	<!-- Smooth Scroll -->
		<a href="#" class="scrollup">&#9650;</a>
	<!-- Smooth Scroll -->
</div>';

	// Ok, save css!!!		
	makecss();
}


// Admin section:
function mycustomcss_admin()
{
	$plugin_page = add_menu_page(__('My Custom CSS Panel','my-custom-css'),__('My Custom CSS','my-custom-css'), 'manage_options', 'my_custom_css', 'mccss_options', plugin_dir_url(__FILE__).'/mccss.png', 61);
	add_action('admin_init', 'mycustomcss_registersetting');
	add_action('admin_head-'. $plugin_page, 'mycustomcss_scripts');
	// Disable "WP Editor" in this page if is active: http://wordpress.org/extend/plugins/wp-editor/
	If (is_plugin_active("wp-editor/wpeditor.php") && $_SERVER['QUERY_STRING'] == 'page=my_custom_css')
	{
		function remove_wpeditor_header_info()
		{
		// Wp Editor Style
		wp_deregister_style('wpeditor');
		wp_deregister_style('fancybox');
		wp_deregister_style('codemirror');
		wp_deregister_style('codemirror_dialog');
		wp_deregister_style('codemirror_themes');
		// Wp Editor Script
		wp_deregister_script('wpeditor');
		wp_deregister_script('wp-editor-posts-jquery');
		wp_deregister_script('fancybox');
		wp_deregister_script('codemirror');
		wp_deregister_script('codemirror_php');
		wp_deregister_script('codemirror_javascript');
		wp_deregister_script('codemirror_css');
		wp_deregister_script('codemirror_xml');
		wp_deregister_script('codemirror_clike');
		wp_deregister_script('codemirror_dialog');
		wp_deregister_script('codemirror_search');
		wp_deregister_script('codemirror_searchcursor');
		wp_deregister_script('codemirror_mustache');
		}
	add_action('admin_init', 'remove_wpeditor_header_info', 20);
	}
}
add_action('admin_menu', 'mycustomcss_admin');
add_action('wp_head', 'mycustomcss_head', 99999);
add_action('admin_print_styles', 'mycustomcss_admin_style');
add_filter('plugin_row_meta', 'add_plugin_meta_links', 10, 2);
add_filter('plugin_action_links_'.plugin_basename(__FILE__).'', 'mycustomcss_links');

?>